import type { ClipDto } from '../../types/clip.js';

export function formatTimestamp(totalSeconds: number): string {
  const seconds = Math.max(0, Math.floor(totalSeconds));
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
}

const titleCase = (value: string) => value.replace(/\b\w/g, (char) => char.toUpperCase());
const bulletList = (items: string[], empty: string) => (items.length ? items.map((item) => `- ${item}`).join('\n') : `_${empty}_`);

export function clipToMarkdown(clip: ClipDto): string {
  const lines: string[] = [];
  const push = (...values: string[]) => lines.push(...values);

  push(`# Reel Analysis`, '');
  push(`**${clip.title}**`, '');
  push(
    `- **Creator:** @${clip.author}`,
    `- **Platform:** ${titleCase(clip.platform)} ${titleCase(clip.mediaType)}`,
    `- **Duration:** ${formatTimestamp(clip.duration)}`,
    `- **Source:** ${clip.originalUrl}`,
    `- **Analyzed:** ${clip.analysisMeta.analyzedAt.slice(0, 10)} (${clip.analysisMeta.provider} · ${clip.analysisMeta.model})`,
    '',
  );

  push('## Summary', '', clip.summary, '');

  push('## Hook', '');
  push(`> ${clip.hook.text || '—'}`, '');
  push(`- **Type:** ${clip.hook.type}`, `- **Score:** ${clip.hook.score}/100`, '');
  if (clip.hook.whyItWorks) push(`**Why it works:** ${clip.hook.whyItWorks}`, '');

  push('## Transcript', '');
  if (clip.transcript.length) {
    for (const segment of clip.transcript) {
      push(`**[${formatTimestamp(segment.start)}–${formatTimestamp(segment.end)}]** ${segment.text}  `);
    }
    push('');
  } else {
    push('_No spoken dialogue detected._', '');
  }

  push('## On-Screen Text', '');
  push(
    clip.onScreenText.length
      ? clip.onScreenText.map((item) => `- **${formatTimestamp(item.timestamp)}** — ${item.text}`).join('\n')
      : '_No on-screen text detected._',
    '',
  );

  push('## Content Structure', '');
  if (clip.structure.length) {
    push('| Stage | Time | Description |', '| --- | --- | --- |');
    for (const section of clip.structure) {
      const description = section.description.replace(/\|/g, '\\|');
      push(`| ${section.stage.toUpperCase()} | ${formatTimestamp(section.start)}–${formatTimestamp(section.end)} | ${description} |`);
    }
    push('');
  } else {
    push('_No structure detected._', '');
  }

  push('## Retention Analysis', '', `**Retention score:** ${clip.retention.score}/100`, '');
  push('### Observations', '', bulletList(clip.retention.observations, 'None recorded.'), '');
  push('### Risk Points', '', bulletList(clip.retention.riskPoints, 'None identified.'), '');

  push('## CTA', '');
  if (clip.cta.text) {
    push(`> ${clip.cta.text}`, '', `- **Type:** ${clip.cta.type}`, `- **Score:** ${clip.cta.score}/100`, '');
  } else {
    push('_No call to action detected._', '');
  }

  push('## Key Takeaways', '', clip.keyTakeaways.map((item, index) => `${index + 1}. ${item}`).join('\n') || '_None._', '');

  push('## Scores', '', '| Metric | Score |', '| --- | --- |');
  push(
    `| Hook | ${clip.scores.hook} |`,
    `| Retention | ${clip.scores.retention} |`,
    `| Structure | ${clip.scores.structure} |`,
    `| CTA | ${clip.scores.cta} |`,
    `| **Overall** | **${clip.scores.overall}** |`,
    '',
    '---',
    '_Generated by ClipScript_',
    '',
  );

  return lines.join('\n');
}
